---
- name: Destroy
  hosts:
    - localhost
  tasks:
    - name: Get libvirt info
      community.libvirt.virt:
        command: info
      register: _libvirt_info

    - name: Destroy VM
      loop: "{{ molecule_yml.platforms }}"
      ansible.builtin.include_tasks: vm.yml
      loop_control:
        loop_var: _platform
        label: "{{ _platform.name_prefix }}{{ _platform.name }}"
