---
- name: Create
  hosts:
    - localhost
  tasks:
    - name: Get libvirt info
      community.libvirt.virt:
        command: info
      register: _libvirt_info

    - name: Create VM
      loop: "{{ molecule_yml.platforms }}"
      ansible.builtin.include_tasks: vm.yml
      loop_control:
        loop_var: _platform
