---
- name: Destroy
  hosts:
    - localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tags:
    - always
  tasks:
    - name: Destroy molecule instance(s)
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      community.docker.docker_container:
        name: "netscaler_server_certificate_{{ item.name }}"
        state: absent
