---
driver:
  name: default
platforms:
  - name: netscaler
    netscaler_version: ${MOLECULE_NETSCALER_VERSION:-13.1-49.15}
    http_port: 33080
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        netscaler_certificate_name: test
        netscaler_certificate_type: self_signed
        netscaler_private_key_passphrase: SecurePass
        netscaler_private_key_filename: test.key
        netscaler_certificate_filename: test.cert
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    # Removed idempotence check, because this scenario tests for idempotence implicitly.
    - side_effect
    - verify
    - cleanup
    - destroy
