---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/server_certificate/.aar_doc.yml
      - roles/server_certificate/README.md
      - roles/server_certificate/meta/argument_specs.yml
      - roles/server_certificate/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.netscaler'
jobs:
  docs_server_certificate:
    name: Generate server_certificate role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.netscaler'
      role_name: 'server_certificate'
